### ISSUE TITLE
Compiler exits with syntax error if the opening syntax stated on README is used

### ISSUE THREAD

**Issue by aledjones** [MastersOfDesaster/Vongpiler#75] opened 2018-01-12 00:08 UTC
The opening expected is "was ist das _fuer_ 1 code? but samples and specs state "was ist das _für_ 1 code?". Got me confused at first.
![18-01-12_7kofl](https://user-images.githubusercontent.com/649142/34853619-00cfd198-f735-11e7-936b-c43173031094.png)

Pls fix in specs and README
Kthxbye xoxo

**Comment by slechte** [comment] 2018-01-12 09:00
Thanks for testing. We are currently preparing a new release which fixes this issue. The problem is that the README in the current master branch is already updated for the release. We hope that we can upload the release today and hope for further feedback from you.

**Comment by benjamin-albrecht** [comment] 2018-01-12 14:53
@aledjones test our new relase. All known bugs are fixed and emojis as variable names are supported. https://github.com/MastersOfDesaster/Vongpiler/releases/tag/1.0-RC.1

**Comment by benjamin-albrecht** [comment] 2018-01-14 17:27
@aledjones we hope it works with the new version as described. That's why we're closing the isssue.

**Closed by benjamin-albrecht** 2018-01-14 17:27 UTC
Labels: question

**Comment by aledjones** [comment] 2018-01-25 23:06
Works as expected! Thx guys. 👍
